name: sistaz_share_web
description: Sistaz Share coming soon page

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # a
  animated_text_kit: ^4.2.1
  another_flushbar: ^1.10.28

  # b
  bcrypt: ^1.1.3

  # c
  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.10.0
  carousel_slider: ^4.0.0
  clipboard: ^0.1.3

  # d
  delayed_display: ^2.0.0
  dots_indicator: ^3.0.0
  demoji: ^2.0.0
  dropdown_button2: ^2.3.9

  # e
  email_validator: ^2.0.1
  expandable: ^5.0.1
  expandable_page_view: ^1.0.17
  entry: ^0.0.9

  # f
  firebase_core: ^2.18.0
  flextras: ^1.0.0
  flick_video_player: ^0.5.0

  # g
  get: ^4.6.1
  gap: ^3.0.0
  get_it: ^7.2.0
  go_router: ^11.1.4
  gradient_widgets: ^0.6.0

  # l
  loader_overlay: ^2.3.1

  # r
  responsive_builder: ^0.7.0
  rounded_loading_button: ^2.1.0

  # t
  transparent_image: ^2.0.0
  textstyle_extensions: ^2.0.0-nullsafety

  # u
  url_launcher: ^6.1.10
  url_strategy: ^0.2.0

  # v
  video_player: ^2.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/gifs/

  fonts:
    - family: MazzardM
      fonts:
        - asset: assets/fonts/MazzardM-Thin.otf
          weight: 100
        - asset: assets/fonts/MazzardM-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/MazzardM-Light.otf
          weight: 300
        - asset: assets/fonts/MazzardM-Regular.otf
          weight: 400
        - asset: assets/fonts/MazzardM-Medium.otf
          weight: 500
        - asset: assets/fonts/MazzardM-SemiBold.otf
          weight: 600
        - asset: assets/fonts/MazzardM-Bold.otf
          weight: 700
        - asset: assets/fonts/MazzardM-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/MazzardM-Black.otf
          weight: 900

    - family: Autography
      fonts:
        - asset: assets/fonts/Autography.otf

    - family: Times-New-Roman
      fonts:
        - asset: assets/fonts/Times-New-Roman.ttf

    - family: Anton
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf
