name: sistaz_share_web
description: Sistaz Share coming soon page

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # a
  animated_text_kit: ^4.2.1
  argon_buttons_flutter: ^1.1.0
  another_flushbar: ^1.10.28

  # c
  cupertino_icons: ^1.0.2
  cloud_firestore: ^3.1.8
  carousel_slider: ^4.0.0

  # d
  delayed_display: ^2.0.0
  dots_indicator: ^2.0.0
  demoji: ^2.0.0

  # e
  email_validator: ^2.0.1

  # f
  flutter_slider_drawer: ^2.0.0
  firebase_core: ^1.12.0

  # g
  get: ^4.6.1

  # p
  provider: ^6.0.2

  # r
  responsive_builder: ^0.4.1

  # t
  transparent_image: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/gifs/

  fonts:
    - family: Mazzard
      fonts:
        - asset: assets/fonts/mazzardm-light.otf
    - family: Autography
      fonts:
        - asset: assets/fonts/Autography.otf
