name: sistaz_share_web
description: Coming soon website of Sistaz Share

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # c
  cupertino_icons: ^1.0.2

  # d
  dots_indicator: ^2.0.0
  delayed_display: ^2.0.0

  # r
  responsive_builder: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Mazzard
      fonts:
        - asset: assets/fonts/mazzardm-light.otf
    - family: Autography
      fonts:
        - asset: assets/fonts/Autography.otf
